# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-31046-leftserv/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::runtime_optimized 1
    set rt::partid xc7vx485tffg1761-2

    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      ./.Xil/Vivado-31046-leftserv/realtime/clk_wiz_0_stub.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/ALUTest.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/decoder3_8.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/mux.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/decoder4_16.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/sevensegment.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/mux_array.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/ClockDivider.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/Registers.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/ProgramMemory.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/PC.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/JumpLogic.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/InstructionMemory.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/DoubleSevenSegment.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/ControlLogic.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/Binary_BCD.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/ALU.v
      /media/KAYDISK2/MISCComputer/ISE_PROJECT/HighLevel.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top HighLevel
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-31046-leftserv/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
