# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mckay/MISCComputer/Vivado_project/Vivado_project.cache/wt [current_project]
set_property parent.project_path /home/mckay/MISCComputer/Vivado_project/Vivado_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.1 [current_project]
add_files -quiet /home/mckay/MISCComputer/Vivado_project/Vivado_project.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/mckay/MISCComputer/Vivado_project/Vivado_project.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /home/mckay/MISCComputer/ISE_PROJECT/ALUTest.v
  /home/mckay/MISCComputer/ISE_PROJECT/decoder3_8.v
  /home/mckay/MISCComputer/ISE_PROJECT/mux.v
  /home/mckay/MISCComputer/ISE_PROJECT/decoder4_16.v
  /home/mckay/MISCComputer/ISE_PROJECT/sevensegment.v
  /home/mckay/MISCComputer/ISE_PROJECT/mux_array.v
  /home/mckay/MISCComputer/ISE_PROJECT/ClockDivider.v
  /home/mckay/MISCComputer/ISE_PROJECT/Registers.v
  /home/mckay/MISCComputer/ISE_PROJECT/ProgramMemory.v
  /home/mckay/MISCComputer/ISE_PROJECT/PC.v
  /home/mckay/MISCComputer/ISE_PROJECT/JumpLogic.v
  /home/mckay/MISCComputer/ISE_PROJECT/InstructionMemory.v
  /home/mckay/MISCComputer/ISE_PROJECT/DoubleSevenSegment.v
  /home/mckay/MISCComputer/ISE_PROJECT/ControlLogic.v
  /home/mckay/MISCComputer/ISE_PROJECT/Binary_BCD.v
  /home/mckay/MISCComputer/ISE_PROJECT/ALU.v
  /home/mckay/MISCComputer/ISE_PROJECT/HighLevel.v
}
read_xdc /home/mckay/MISCComputer/Vivado_project/Vivado_project.srcs/constrs_1/new/testConstaints.xdc
set_property used_in_implementation false [get_files /home/mckay/MISCComputer/Vivado_project/Vivado_project.srcs/constrs_1/new/testConstaints.xdc]

catch { write_hwdef -file HighLevel.hwdef }
synth_design -top HighLevel -part xc7vx485tffg1761-2 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
write_checkpoint -noxdef HighLevel.dcp
catch { report_utilization -file HighLevel_utilization_synth.rpt -pb HighLevel_utilization_synth.pb }
